SELECT 
    ugu.USER_ID,
    ugu.NICKNAME,
    ugb.TOTAL_SALES
FROM (
    SELECT
        WRITER_ID,
        SUM(PRICE) AS 'TOTAL_SALES'
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) AS ugb
INNER JOIN USED_GOODS_USER  AS ugu
ON ugb.WRITER_ID = ugu.USER_ID
ORDER BY 3 ASC